apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversational-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversational-agent
  template:
    metadata:
      labels:
        app: conversational-agent
    spec:
      containers:
      - name: conversational-agent
        image: <your-registry>/conversational-agent:latest
        ports:
        - containerPort: 8009
          name: tcp
        - containerPort: 8010
          name: wss
        - containerPort: 8011
          name: status
        env:
        - name: IBM_STT_API_KEY
          valueFrom:
            secretKeyRef:
              name: ibm-credentials
              key: stt-api-key
        - name: IBM_STT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: ibm-credentials
              key: stt-service-url
        - name: IBM_TTS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ibm-credentials
              key: tts-api-key
        - name: IBM_TTS_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: ibm-credentials
              key: tts-service-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: api-key