apiVersion: v1
kind: Secret
metadata:
  name: ibm-credentials
type: Opaque
stringData:
  stt-api-key: "<your-ibm-stt-api-key>"
  stt-service-url: "<your-ibm-stt-service-url>"
  tts-api-key: "<your-ibm-tts-api-key>"
  tts-service-url: "<your-ibm-tts-service-url>"
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
type: Opaque
stringData:
  api-key: "<your-openai-api-key>"