apiVersion: v1
kind: Service
metadata:
  name: conversational-agent
spec:
  type: LoadBalancer
  ports:
  - port: 8009
    targetPort: 8009
    name: tcp
  - port: 8010
    targetPort: 8010
    name: wss
  - port: 8011
    targetPort: 8011
    name: status
  selector:
    app: conversational-agent